baseURL = "http://www.questionflow.org/"
languageCode = "en-us"
title = "QuestionFlow"
theme = "minimal"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
GoogleAnalytics = "UA-107291782-1"

[params]
    author = "Evgeni Chasnovski"
    description = "Analysis workflow powered by questions"
    githubUsername = "echasnovski"
    accent = "#000080"
    showBorder = false
    backgroundColor = "#f4ffff"
    font = "Ubuntu" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "idea"
    highlightLanguages = ["yaml"]
    js = ["/js/custom.r.min.js"]
    
    paginate = 10
    
[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Archive"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://twitter.com/questionflow/"
    name = "twitter-square"
    weight = 1

[[menu.icon]]
    url = "https://github.com/echasnovski/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/echasnovski/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.stackoverflow.com/users/7360839/echasnovski"
    name = "stack-overflow"
    weight = 4
